<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Blueberry\\Core\\Controller\\AuthController' => $baseDir . '/src/Controller/AuthController.php',
    'Blueberry\\Core\\Controller\\BaseController' => $baseDir . '/src/Controller/BaseController.php',
    'Blueberry\\Core\\Controller\\RoleController' => $baseDir . '/src/Controller/RoleController.php',
    'Blueberry\\Core\\Controller\\ScopeController' => $baseDir . '/src/Controller/ScopeController.php',
    'Blueberry\\Core\\Controller\\UserController' => $baseDir . '/src/Controller/UserController.php',
    'Blueberry\\Core\\Middleware\\AuthMiddleware' => $baseDir . '/src/Middleware/AuthMiddleware.php',
    'Blueberry\\Core\\Middleware\\RouteScopeMiddleWare' => $baseDir . '/src/Middleware/RouteScopeMiddleware.php',
    'Blueberry\\Core\\Model\\Role' => $baseDir . '/src/Model/Role.php',
    'Blueberry\\Core\\Model\\Scope' => $baseDir . '/src/Model/Scope.php',
    'Blueberry\\Core\\Model\\User' => $baseDir . '/src/Model/User.php',
);
